In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("E:\geethanjaliexternship\Fish.csv")

In [3]:
data.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
data.isnull()

     Species  Weight  Length1  Length2  Length3  Height  Width
0      False   False    False    False    False   False  False
1      False   False    False    False    False   False  False
2      False   False    False    False    False   False  False
3      False   False    False    False    False   False  False
4      False   False    False    False    False   False  False
5      False   False    False    False    False   False  False
6      False   False    False    False    False   False  False
7      False   False    False    False    False   False  False
8      False   False    False    False    False   False  False
9      False   False    False    False    False   False  False
10     False   False    False    False    False   False  False
11     False   False    False    False    False   False  False
12     False   False    False    False    False   False  False
13     False   False    False    False    False   False  False
14     False   False    False    False    False   False  False
15     False   False    False    False    False   False  False
16     False   False    False    False    False   False  False
17     False   False    False    False    False   False  False
18     False   False    False    False    False   False  False
19     False   False    False    False    False   False  False
20     False   False    False    False    False   False  False
21     False   False    False    False    False   False  False
22     False   False    False    False    False   False  False
23     False   False    False    False    False   False  False
24     False   False    False    False    False   False  False
25     False   False    False    False    False   False  False
26     False   False    False    False    False   False  False
27     False   False    False    False    False   False  False
28     False   False    False    False    False   False  False
29     False   False    False    False    False   False  False
..       ...     ...      ...      ...      ...     ...    ...
129    False   False    False    False    False   False  False
130    False   False    False    False    False   False  False
131    False   False    False    False    False   False  False
132    False   False    False    False    False   False  False
133    False   False    False    False    False   False  False
134    False   False    False    False    False   False  False
135    False   False    False    False    False   False  False
136    False   False    False    False    False   False  False
137    False   False    False    False    False   False  False
138    False   False    False    False    False   False  False
139    False   False    False    False    False   False  False
140    False   False    False    False    False   False  False
141    False   False    False    False    False   False  False
142    False   False    False    False    False   False  False
143    False   False    False    False    False   False  False
144    False   False    False    False    False   False  False
145    False   False    False    False    False   False  False
146    False   False    False    False    False   False  False
147    False   False    False    False    False   False  False
148    False   False    False    False    False   False  False
149    False   False    False    False    False   False  False
150    False   False    False    False    False   False  False
151    False   False    False    False    False   False  False
152    False   False    False    False    False   False  False
153    False   False    False    False    False   False  False
154    False   False    False    False    False   False  False
155    False   False    False    False    False   False  False
156    False   False    False    False    False   False  False
157    False   False    False    False    False   False  False
158    False   False    False    False    False   False  False

[159 rows x 7 columns]

In [5]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
Species    159 non-null object
Weight     159 non-null float64
Length1    159 non-null float64
Length2    159 non-null float64
Length3    159 non-null float64
Height     159 non-null float64
Width      159 non-null float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

In [7]:
data=pd.DataFrame(data)

In [8]:
v=data[list(data.columns)[1]] 
data=data.drop(['Weight'],axis=1) 
data.insert(6,'Weight',v)

In [9]:
data.head()

  Species  Length1  Length2  Length3   Height   Width  Weight
0   Bream     23.2     25.4     30.0  11.5200  4.0200   242.0
1   Bream     24.0     26.3     31.2  12.4800  4.3056   290.0
2   Bream     23.9     26.5     31.1  12.3778  4.6961   340.0
3   Bream     26.3     29.0     33.5  12.7300  4.4555   363.0
4   Bream     26.5     29.0     34.0  12.4440  5.1340   430.0

In [10]:
x=data.iloc[:,0:6]
y=data.iloc[:,6]

In [11]:
x

    Species  Length1  Length2  Length3   Height   Width
0     Bream     23.2     25.4     30.0  11.5200  4.0200
1     Bream     24.0     26.3     31.2  12.4800  4.3056
2     Bream     23.9     26.5     31.1  12.3778  4.6961
3     Bream     26.3     29.0     33.5  12.7300  4.4555
4     Bream     26.5     29.0     34.0  12.4440  5.1340
5     Bream     26.8     29.7     34.7  13.6024  4.9274
6     Bream     26.8     29.7     34.5  14.1795  5.2785
7     Bream     27.6     30.0     35.0  12.6700  4.6900
8     Bream     27.6     30.0     35.1  14.0049  4.8438
9     Bream     28.5     30.7     36.2  14.2266  4.9594
10    Bream     28.4     31.0     36.2  14.2628  5.1042
11    Bream     28.7     31.0     36.2  14.3714  4.8146
12    Bream     29.1     31.5     36.4  13.7592  4.3680
13    Bream     29.5     32.0     37.3  13.9129  5.0728
14    Bream     29.4     32.0     37.2  14.9544  5.1708
15    Bream     29.4     32.0     37.2  15.4380  5.5800
16    Bream     30.4     33.0     38.3  14.8604  5.2854
17    Bream     30.4     33.0     38.5  14.9380  5.1975
18    Bream     30.9     33.5     38.6  15.6330  5.1338
19    Bream     31.0     33.5     38.7  14.4738  5.7276
20    Bream     31.3     34.0     39.5  15.1285  5.5695
21    Bream     31.4     34.0     39.2  15.9936  5.3704
22    Bream     31.5     34.5     39.7  15.5227  5.2801
23    Bream     31.8     35.0     40.6  15.4686  6.1306
24    Bream     31.9     35.0     40.5  16.2405  5.5890
25    Bream     31.8     35.0     40.9  16.3600  6.0532
26    Bream     32.0     35.0     40.6  16.3618  6.0900
27    Bream     32.7     36.0     41.5  16.5170  5.8515
28    Bream     32.8     36.0     41.6  16.8896  6.1984
29    Bream     33.5     37.0     42.6  18.9570  6.6030
..      ...      ...      ...      ...      ...     ...
129    Pike     31.7     34.0     37.8   5.7078  4.1580
130    Pike     32.7     35.0     38.8   5.9364  4.3844
131    Pike     34.8     37.3     39.8   6.2884  4.0198
132    Pike     35.5     38.0     40.5   7.2900  4.5765
133    Pike     36.0     38.5     41.0   6.3960  3.9770
134    Pike     40.0     42.5     45.5   7.2800  4.3225
135    Pike     40.0     42.5     45.5   6.8250  4.4590
136    Pike     40.1     43.0     45.8   7.7860  5.1296
137    Pike     42.0     45.0     48.0   6.9600  4.8960
138    Pike     43.2     46.0     48.7   7.7920  4.8700
139    Pike     44.8     48.0     51.2   7.6800  5.3760
140    Pike     48.3     51.7     55.1   8.9262  6.1712
141    Pike     52.0     56.0     59.7  10.6863  6.9849
142    Pike     56.0     60.0     64.0   9.6000  6.1440
143    Pike     56.0     60.0     64.0   9.6000  6.1440
144    Pike     59.0     63.4     68.0  10.8120  7.4800
145   Smelt      9.3      9.8     10.8   1.7388  1.0476
146   Smelt     10.0     10.5     11.6   1.9720  1.1600
147   Smelt     10.1     10.6     11.6   1.7284  1.1484
148   Smelt     10.4     11.0     12.0   2.1960  1.3800
149   Smelt     10.7     11.2     12.4   2.0832  1.2772
150   Smelt     10.8     11.3     12.6   1.9782  1.2852
151   Smelt     11.3     11.8     13.1   2.2139  1.2838
152   Smelt     11.3     11.8     13.1   2.2139  1.1659
153   Smelt     11.4     12.0     13.2   2.2044  1.1484
154   Smelt     11.5     12.2     13.4   2.0904  1.3936
155   Smelt     11.7     12.4     13.5   2.4300  1.2690
156   Smelt     12.1     13.0     13.8   2.2770  1.2558
157   Smelt     13.2     14.3     15.2   2.8728  2.0672
158   Smelt     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [12]:
x=data.iloc[:,0:6].values
y=data.iloc[:,6].values

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [14]:
x

array([[1.0, 0.0, 0.0, ..., 30.0, 11.52, 4.02],
       [1.0, 0.0, 0.0, ..., 31.2, 12.48, 4.3056],
       [1.0, 0.0, 0.0, ..., 31.1, 12.3778, 4.6961],
       ...,
       [0.0, 0.0, 0.0, ..., 13.8, 2.2769999999999997, 1.2558],
       [0.0, 0.0, 0.0, ..., 15.2, 2.8728, 2.0672],
       [0.0, 0.0, 0.0, ..., 16.2, 2.9322, 1.8792]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [16]:
x_train.shape

(127, 12)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
ypred=mlr.predict(x_test)

In [20]:
from sklearn.metrics import r2_score

In [21]:
accuracy=r2_score(ypred,y_test)

In [22]:
accuracy

0.9475711630530974

In [23]:
mlr.predict(ct.transform([["Bream",248.0,23.2,65.4,50.0,11.5200,8.0200]]))

array([-15210.09927793])

In [24]:
mlr.predict(ct.transform([["Smelt",23.2,25.4,30.0,11.5200,4.0200]]))

array([694.28515551])